// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sita_operators.proto

#ifndef PROTOBUF_sita_5foperators_2eproto__INCLUDED
#define PROTOBUF_sita_5foperators_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "sita_utils.pb.h"
// @@protoc_insertion_point(includes)

namespace sita {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_sita_5foperators_2eproto();
void protobuf_AssignDesc_sita_5foperators_2eproto();
void protobuf_ShutdownFile_sita_5foperators_2eproto();

class GraphParameter;
class OperatorParameter;
class AddOpParameter;
class ConvolutionOpParameter;

// ===================================================================

class GraphParameter : public ::google::protobuf::Message {
 public:
  GraphParameter();
  virtual ~GraphParameter();

  GraphParameter(const GraphParameter& from);

  inline GraphParameter& operator=(const GraphParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GraphParameter& default_instance();

  void Swap(GraphParameter* other);

  // implements Message ----------------------------------------------

  GraphParameter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GraphParameter& from);
  void MergeFrom(const GraphParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // repeated .sita.OperatorParameter operatordef = 2;
  inline int operatordef_size() const;
  inline void clear_operatordef();
  static const int kOperatordefFieldNumber = 2;
  inline const ::sita::OperatorParameter& operatordef(int index) const;
  inline ::sita::OperatorParameter* mutable_operatordef(int index);
  inline ::sita::OperatorParameter* add_operatordef();
  inline const ::google::protobuf::RepeatedPtrField< ::sita::OperatorParameter >&
      operatordef() const;
  inline ::google::protobuf::RepeatedPtrField< ::sita::OperatorParameter >*
      mutable_operatordef();

  // @@protoc_insertion_point(class_scope:sita.GraphParameter)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::sita::OperatorParameter > operatordef_;
  friend void  protobuf_AddDesc_sita_5foperators_2eproto();
  friend void protobuf_AssignDesc_sita_5foperators_2eproto();
  friend void protobuf_ShutdownFile_sita_5foperators_2eproto();

  void InitAsDefaultInstance();
  static GraphParameter* default_instance_;
};
// -------------------------------------------------------------------

class OperatorParameter : public ::google::protobuf::Message {
 public:
  OperatorParameter();
  virtual ~OperatorParameter();

  OperatorParameter(const OperatorParameter& from);

  inline OperatorParameter& operator=(const OperatorParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OperatorParameter& default_instance();

  void Swap(OperatorParameter* other);

  // implements Message ----------------------------------------------

  OperatorParameter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OperatorParameter& from);
  void MergeFrom(const OperatorParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline const ::std::string& type() const;
  inline void set_type(const ::std::string& value);
  inline void set_type(const char* value);
  inline void set_type(const char* value, size_t size);
  inline ::std::string* mutable_type();
  inline ::std::string* release_type();
  inline void set_allocated_type(::std::string* type);

  // repeated string input = 3;
  inline int input_size() const;
  inline void clear_input();
  static const int kInputFieldNumber = 3;
  inline const ::std::string& input(int index) const;
  inline ::std::string* mutable_input(int index);
  inline void set_input(int index, const ::std::string& value);
  inline void set_input(int index, const char* value);
  inline void set_input(int index, const char* value, size_t size);
  inline ::std::string* add_input();
  inline void add_input(const ::std::string& value);
  inline void add_input(const char* value);
  inline void add_input(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& input() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_input();

  // repeated string output = 4;
  inline int output_size() const;
  inline void clear_output();
  static const int kOutputFieldNumber = 4;
  inline const ::std::string& output(int index) const;
  inline ::std::string* mutable_output(int index);
  inline void set_output(int index, const ::std::string& value);
  inline void set_output(int index, const char* value);
  inline void set_output(int index, const char* value, size_t size);
  inline ::std::string* add_output();
  inline void add_output(const ::std::string& value);
  inline void add_output(const char* value);
  inline void add_output(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& output() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_output();

  // repeated float loss_weight = 5;
  inline int loss_weight_size() const;
  inline void clear_loss_weight();
  static const int kLossWeightFieldNumber = 5;
  inline float loss_weight(int index) const;
  inline void set_loss_weight(int index, float value);
  inline void add_loss_weight(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      loss_weight() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_loss_weight();

  // repeated .sita.ParamConfig param = 6;
  inline int param_size() const;
  inline void clear_param();
  static const int kParamFieldNumber = 6;
  inline const ::sita::ParamConfig& param(int index) const;
  inline ::sita::ParamConfig* mutable_param(int index);
  inline ::sita::ParamConfig* add_param();
  inline const ::google::protobuf::RepeatedPtrField< ::sita::ParamConfig >&
      param() const;
  inline ::google::protobuf::RepeatedPtrField< ::sita::ParamConfig >*
      mutable_param();

  // optional .sita.AddOpParameter add_op_param = 100;
  inline bool has_add_op_param() const;
  inline void clear_add_op_param();
  static const int kAddOpParamFieldNumber = 100;
  inline const ::sita::AddOpParameter& add_op_param() const;
  inline ::sita::AddOpParameter* mutable_add_op_param();
  inline ::sita::AddOpParameter* release_add_op_param();
  inline void set_allocated_add_op_param(::sita::AddOpParameter* add_op_param);

  // optional .sita.ConvolutionOpParameter convolution_op_param = 101;
  inline bool has_convolution_op_param() const;
  inline void clear_convolution_op_param();
  static const int kConvolutionOpParamFieldNumber = 101;
  inline const ::sita::ConvolutionOpParameter& convolution_op_param() const;
  inline ::sita::ConvolutionOpParameter* mutable_convolution_op_param();
  inline ::sita::ConvolutionOpParameter* release_convolution_op_param();
  inline void set_allocated_convolution_op_param(::sita::ConvolutionOpParameter* convolution_op_param);

  // @@protoc_insertion_point(class_scope:sita.OperatorParameter)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_add_op_param();
  inline void clear_has_add_op_param();
  inline void set_has_convolution_op_param();
  inline void clear_has_convolution_op_param();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::std::string* type_;
  ::google::protobuf::RepeatedPtrField< ::std::string> input_;
  ::google::protobuf::RepeatedPtrField< ::std::string> output_;
  ::google::protobuf::RepeatedField< float > loss_weight_;
  ::google::protobuf::RepeatedPtrField< ::sita::ParamConfig > param_;
  ::sita::AddOpParameter* add_op_param_;
  ::sita::ConvolutionOpParameter* convolution_op_param_;
  friend void  protobuf_AddDesc_sita_5foperators_2eproto();
  friend void protobuf_AssignDesc_sita_5foperators_2eproto();
  friend void protobuf_ShutdownFile_sita_5foperators_2eproto();

  void InitAsDefaultInstance();
  static OperatorParameter* default_instance_;
};
// -------------------------------------------------------------------

class AddOpParameter : public ::google::protobuf::Message {
 public:
  AddOpParameter();
  virtual ~AddOpParameter();

  AddOpParameter(const AddOpParameter& from);

  inline AddOpParameter& operator=(const AddOpParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddOpParameter& default_instance();

  void Swap(AddOpParameter* other);

  // implements Message ----------------------------------------------

  AddOpParameter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddOpParameter& from);
  void MergeFrom(const AddOpParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 pad_h = 1 [default = 0];
  inline bool has_pad_h() const;
  inline void clear_pad_h();
  static const int kPadHFieldNumber = 1;
  inline ::google::protobuf::uint32 pad_h() const;
  inline void set_pad_h(::google::protobuf::uint32 value);

  // optional uint32 pad_w = 2 [default = 0];
  inline bool has_pad_w() const;
  inline void clear_pad_w();
  static const int kPadWFieldNumber = 2;
  inline ::google::protobuf::uint32 pad_w() const;
  inline void set_pad_w(::google::protobuf::uint32 value);

  // optional uint32 kernel_h = 3;
  inline bool has_kernel_h() const;
  inline void clear_kernel_h();
  static const int kKernelHFieldNumber = 3;
  inline ::google::protobuf::uint32 kernel_h() const;
  inline void set_kernel_h(::google::protobuf::uint32 value);

  // optional uint32 kernel_w = 4;
  inline bool has_kernel_w() const;
  inline void clear_kernel_w();
  static const int kKernelWFieldNumber = 4;
  inline ::google::protobuf::uint32 kernel_w() const;
  inline void set_kernel_w(::google::protobuf::uint32 value);

  // optional uint32 stride_h = 5;
  inline bool has_stride_h() const;
  inline void clear_stride_h();
  static const int kStrideHFieldNumber = 5;
  inline ::google::protobuf::uint32 stride_h() const;
  inline void set_stride_h(::google::protobuf::uint32 value);

  // optional uint32 stride_w = 6;
  inline bool has_stride_w() const;
  inline void clear_stride_w();
  static const int kStrideWFieldNumber = 6;
  inline ::google::protobuf::uint32 stride_w() const;
  inline void set_stride_w(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:sita.AddOpParameter)
 private:
  inline void set_has_pad_h();
  inline void clear_has_pad_h();
  inline void set_has_pad_w();
  inline void clear_has_pad_w();
  inline void set_has_kernel_h();
  inline void clear_has_kernel_h();
  inline void set_has_kernel_w();
  inline void clear_has_kernel_w();
  inline void set_has_stride_h();
  inline void clear_has_stride_h();
  inline void set_has_stride_w();
  inline void clear_has_stride_w();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 pad_h_;
  ::google::protobuf::uint32 pad_w_;
  ::google::protobuf::uint32 kernel_h_;
  ::google::protobuf::uint32 kernel_w_;
  ::google::protobuf::uint32 stride_h_;
  ::google::protobuf::uint32 stride_w_;
  friend void  protobuf_AddDesc_sita_5foperators_2eproto();
  friend void protobuf_AssignDesc_sita_5foperators_2eproto();
  friend void protobuf_ShutdownFile_sita_5foperators_2eproto();

  void InitAsDefaultInstance();
  static AddOpParameter* default_instance_;
};
// -------------------------------------------------------------------

class ConvolutionOpParameter : public ::google::protobuf::Message {
 public:
  ConvolutionOpParameter();
  virtual ~ConvolutionOpParameter();

  ConvolutionOpParameter(const ConvolutionOpParameter& from);

  inline ConvolutionOpParameter& operator=(const ConvolutionOpParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConvolutionOpParameter& default_instance();

  void Swap(ConvolutionOpParameter* other);

  // implements Message ----------------------------------------------

  ConvolutionOpParameter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConvolutionOpParameter& from);
  void MergeFrom(const ConvolutionOpParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 num_output = 1;
  inline bool has_num_output() const;
  inline void clear_num_output();
  static const int kNumOutputFieldNumber = 1;
  inline ::google::protobuf::uint32 num_output() const;
  inline void set_num_output(::google::protobuf::uint32 value);

  // optional bool bias_term = 2 [default = true];
  inline bool has_bias_term() const;
  inline void clear_bias_term();
  static const int kBiasTermFieldNumber = 2;
  inline bool bias_term() const;
  inline void set_bias_term(bool value);

  // optional uint32 pad = 3;
  inline bool has_pad() const;
  inline void clear_pad();
  static const int kPadFieldNumber = 3;
  inline ::google::protobuf::uint32 pad() const;
  inline void set_pad(::google::protobuf::uint32 value);

  // optional uint32 kernel_size = 4;
  inline bool has_kernel_size() const;
  inline void clear_kernel_size();
  static const int kKernelSizeFieldNumber = 4;
  inline ::google::protobuf::uint32 kernel_size() const;
  inline void set_kernel_size(::google::protobuf::uint32 value);

  // optional uint32 stride = 5;
  inline bool has_stride() const;
  inline void clear_stride();
  static const int kStrideFieldNumber = 5;
  inline ::google::protobuf::uint32 stride() const;
  inline void set_stride(::google::protobuf::uint32 value);

  // optional uint32 dilation = 6 [default = 1];
  inline bool has_dilation() const;
  inline void clear_dilation();
  static const int kDilationFieldNumber = 6;
  inline ::google::protobuf::uint32 dilation() const;
  inline void set_dilation(::google::protobuf::uint32 value);

  // optional uint32 pad_h = 7 [default = 0];
  inline bool has_pad_h() const;
  inline void clear_pad_h();
  static const int kPadHFieldNumber = 7;
  inline ::google::protobuf::uint32 pad_h() const;
  inline void set_pad_h(::google::protobuf::uint32 value);

  // optional uint32 pad_w = 8 [default = 0];
  inline bool has_pad_w() const;
  inline void clear_pad_w();
  static const int kPadWFieldNumber = 8;
  inline ::google::protobuf::uint32 pad_w() const;
  inline void set_pad_w(::google::protobuf::uint32 value);

  // optional uint32 kernel_h = 9 [default = 3];
  inline bool has_kernel_h() const;
  inline void clear_kernel_h();
  static const int kKernelHFieldNumber = 9;
  inline ::google::protobuf::uint32 kernel_h() const;
  inline void set_kernel_h(::google::protobuf::uint32 value);

  // optional uint32 kernel_w = 10 [default = 3];
  inline bool has_kernel_w() const;
  inline void clear_kernel_w();
  static const int kKernelWFieldNumber = 10;
  inline ::google::protobuf::uint32 kernel_w() const;
  inline void set_kernel_w(::google::protobuf::uint32 value);

  // optional uint32 stride_h = 11;
  inline bool has_stride_h() const;
  inline void clear_stride_h();
  static const int kStrideHFieldNumber = 11;
  inline ::google::protobuf::uint32 stride_h() const;
  inline void set_stride_h(::google::protobuf::uint32 value);

  // optional uint32 stride_w = 12;
  inline bool has_stride_w() const;
  inline void clear_stride_w();
  static const int kStrideWFieldNumber = 12;
  inline ::google::protobuf::uint32 stride_w() const;
  inline void set_stride_w(::google::protobuf::uint32 value);

  // optional uint32 group = 13 [default = 1];
  inline bool has_group() const;
  inline void clear_group();
  static const int kGroupFieldNumber = 13;
  inline ::google::protobuf::uint32 group() const;
  inline void set_group(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:sita.ConvolutionOpParameter)
 private:
  inline void set_has_num_output();
  inline void clear_has_num_output();
  inline void set_has_bias_term();
  inline void clear_has_bias_term();
  inline void set_has_pad();
  inline void clear_has_pad();
  inline void set_has_kernel_size();
  inline void clear_has_kernel_size();
  inline void set_has_stride();
  inline void clear_has_stride();
  inline void set_has_dilation();
  inline void clear_has_dilation();
  inline void set_has_pad_h();
  inline void clear_has_pad_h();
  inline void set_has_pad_w();
  inline void clear_has_pad_w();
  inline void set_has_kernel_h();
  inline void clear_has_kernel_h();
  inline void set_has_kernel_w();
  inline void clear_has_kernel_w();
  inline void set_has_stride_h();
  inline void clear_has_stride_h();
  inline void set_has_stride_w();
  inline void clear_has_stride_w();
  inline void set_has_group();
  inline void clear_has_group();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 num_output_;
  bool bias_term_;
  ::google::protobuf::uint32 pad_;
  ::google::protobuf::uint32 kernel_size_;
  ::google::protobuf::uint32 stride_;
  ::google::protobuf::uint32 dilation_;
  ::google::protobuf::uint32 pad_h_;
  ::google::protobuf::uint32 pad_w_;
  ::google::protobuf::uint32 kernel_h_;
  ::google::protobuf::uint32 kernel_w_;
  ::google::protobuf::uint32 stride_h_;
  ::google::protobuf::uint32 stride_w_;
  ::google::protobuf::uint32 group_;
  friend void  protobuf_AddDesc_sita_5foperators_2eproto();
  friend void protobuf_AssignDesc_sita_5foperators_2eproto();
  friend void protobuf_ShutdownFile_sita_5foperators_2eproto();

  void InitAsDefaultInstance();
  static ConvolutionOpParameter* default_instance_;
};
// ===================================================================


// ===================================================================

// GraphParameter

// optional string name = 1;
inline bool GraphParameter::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GraphParameter::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GraphParameter::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GraphParameter::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& GraphParameter::name() const {
  // @@protoc_insertion_point(field_get:sita.GraphParameter.name)
  return *name_;
}
inline void GraphParameter::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:sita.GraphParameter.name)
}
inline void GraphParameter::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:sita.GraphParameter.name)
}
inline void GraphParameter::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sita.GraphParameter.name)
}
inline ::std::string* GraphParameter::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:sita.GraphParameter.name)
  return name_;
}
inline ::std::string* GraphParameter::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GraphParameter::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:sita.GraphParameter.name)
}

// repeated .sita.OperatorParameter operatordef = 2;
inline int GraphParameter::operatordef_size() const {
  return operatordef_.size();
}
inline void GraphParameter::clear_operatordef() {
  operatordef_.Clear();
}
inline const ::sita::OperatorParameter& GraphParameter::operatordef(int index) const {
  // @@protoc_insertion_point(field_get:sita.GraphParameter.operatordef)
  return operatordef_.Get(index);
}
inline ::sita::OperatorParameter* GraphParameter::mutable_operatordef(int index) {
  // @@protoc_insertion_point(field_mutable:sita.GraphParameter.operatordef)
  return operatordef_.Mutable(index);
}
inline ::sita::OperatorParameter* GraphParameter::add_operatordef() {
  // @@protoc_insertion_point(field_add:sita.GraphParameter.operatordef)
  return operatordef_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::sita::OperatorParameter >&
GraphParameter::operatordef() const {
  // @@protoc_insertion_point(field_list:sita.GraphParameter.operatordef)
  return operatordef_;
}
inline ::google::protobuf::RepeatedPtrField< ::sita::OperatorParameter >*
GraphParameter::mutable_operatordef() {
  // @@protoc_insertion_point(field_mutable_list:sita.GraphParameter.operatordef)
  return &operatordef_;
}

// -------------------------------------------------------------------

// OperatorParameter

// optional string name = 1;
inline bool OperatorParameter::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OperatorParameter::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OperatorParameter::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OperatorParameter::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& OperatorParameter::name() const {
  // @@protoc_insertion_point(field_get:sita.OperatorParameter.name)
  return *name_;
}
inline void OperatorParameter::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:sita.OperatorParameter.name)
}
inline void OperatorParameter::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:sita.OperatorParameter.name)
}
inline void OperatorParameter::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sita.OperatorParameter.name)
}
inline ::std::string* OperatorParameter::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:sita.OperatorParameter.name)
  return name_;
}
inline ::std::string* OperatorParameter::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OperatorParameter::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:sita.OperatorParameter.name)
}

// optional string type = 2;
inline bool OperatorParameter::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OperatorParameter::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OperatorParameter::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OperatorParameter::clear_type() {
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_->clear();
  }
  clear_has_type();
}
inline const ::std::string& OperatorParameter::type() const {
  // @@protoc_insertion_point(field_get:sita.OperatorParameter.type)
  return *type_;
}
inline void OperatorParameter::set_type(const ::std::string& value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(value);
  // @@protoc_insertion_point(field_set:sita.OperatorParameter.type)
}
inline void OperatorParameter::set_type(const char* value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(value);
  // @@protoc_insertion_point(field_set_char:sita.OperatorParameter.type)
}
inline void OperatorParameter::set_type(const char* value, size_t size) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sita.OperatorParameter.type)
}
inline ::std::string* OperatorParameter::mutable_type() {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:sita.OperatorParameter.type)
  return type_;
}
inline ::std::string* OperatorParameter::release_type() {
  clear_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = type_;
    type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void OperatorParameter::set_allocated_type(::std::string* type) {
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete type_;
  }
  if (type) {
    set_has_type();
    type_ = type;
  } else {
    clear_has_type();
    type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:sita.OperatorParameter.type)
}

// repeated string input = 3;
inline int OperatorParameter::input_size() const {
  return input_.size();
}
inline void OperatorParameter::clear_input() {
  input_.Clear();
}
inline const ::std::string& OperatorParameter::input(int index) const {
  // @@protoc_insertion_point(field_get:sita.OperatorParameter.input)
  return input_.Get(index);
}
inline ::std::string* OperatorParameter::mutable_input(int index) {
  // @@protoc_insertion_point(field_mutable:sita.OperatorParameter.input)
  return input_.Mutable(index);
}
inline void OperatorParameter::set_input(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:sita.OperatorParameter.input)
  input_.Mutable(index)->assign(value);
}
inline void OperatorParameter::set_input(int index, const char* value) {
  input_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sita.OperatorParameter.input)
}
inline void OperatorParameter::set_input(int index, const char* value, size_t size) {
  input_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sita.OperatorParameter.input)
}
inline ::std::string* OperatorParameter::add_input() {
  return input_.Add();
}
inline void OperatorParameter::add_input(const ::std::string& value) {
  input_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sita.OperatorParameter.input)
}
inline void OperatorParameter::add_input(const char* value) {
  input_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sita.OperatorParameter.input)
}
inline void OperatorParameter::add_input(const char* value, size_t size) {
  input_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sita.OperatorParameter.input)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
OperatorParameter::input() const {
  // @@protoc_insertion_point(field_list:sita.OperatorParameter.input)
  return input_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
OperatorParameter::mutable_input() {
  // @@protoc_insertion_point(field_mutable_list:sita.OperatorParameter.input)
  return &input_;
}

// repeated string output = 4;
inline int OperatorParameter::output_size() const {
  return output_.size();
}
inline void OperatorParameter::clear_output() {
  output_.Clear();
}
inline const ::std::string& OperatorParameter::output(int index) const {
  // @@protoc_insertion_point(field_get:sita.OperatorParameter.output)
  return output_.Get(index);
}
inline ::std::string* OperatorParameter::mutable_output(int index) {
  // @@protoc_insertion_point(field_mutable:sita.OperatorParameter.output)
  return output_.Mutable(index);
}
inline void OperatorParameter::set_output(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:sita.OperatorParameter.output)
  output_.Mutable(index)->assign(value);
}
inline void OperatorParameter::set_output(int index, const char* value) {
  output_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sita.OperatorParameter.output)
}
inline void OperatorParameter::set_output(int index, const char* value, size_t size) {
  output_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sita.OperatorParameter.output)
}
inline ::std::string* OperatorParameter::add_output() {
  return output_.Add();
}
inline void OperatorParameter::add_output(const ::std::string& value) {
  output_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sita.OperatorParameter.output)
}
inline void OperatorParameter::add_output(const char* value) {
  output_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sita.OperatorParameter.output)
}
inline void OperatorParameter::add_output(const char* value, size_t size) {
  output_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sita.OperatorParameter.output)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
OperatorParameter::output() const {
  // @@protoc_insertion_point(field_list:sita.OperatorParameter.output)
  return output_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
OperatorParameter::mutable_output() {
  // @@protoc_insertion_point(field_mutable_list:sita.OperatorParameter.output)
  return &output_;
}

// repeated float loss_weight = 5;
inline int OperatorParameter::loss_weight_size() const {
  return loss_weight_.size();
}
inline void OperatorParameter::clear_loss_weight() {
  loss_weight_.Clear();
}
inline float OperatorParameter::loss_weight(int index) const {
  // @@protoc_insertion_point(field_get:sita.OperatorParameter.loss_weight)
  return loss_weight_.Get(index);
}
inline void OperatorParameter::set_loss_weight(int index, float value) {
  loss_weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:sita.OperatorParameter.loss_weight)
}
inline void OperatorParameter::add_loss_weight(float value) {
  loss_weight_.Add(value);
  // @@protoc_insertion_point(field_add:sita.OperatorParameter.loss_weight)
}
inline const ::google::protobuf::RepeatedField< float >&
OperatorParameter::loss_weight() const {
  // @@protoc_insertion_point(field_list:sita.OperatorParameter.loss_weight)
  return loss_weight_;
}
inline ::google::protobuf::RepeatedField< float >*
OperatorParameter::mutable_loss_weight() {
  // @@protoc_insertion_point(field_mutable_list:sita.OperatorParameter.loss_weight)
  return &loss_weight_;
}

// repeated .sita.ParamConfig param = 6;
inline int OperatorParameter::param_size() const {
  return param_.size();
}
inline void OperatorParameter::clear_param() {
  param_.Clear();
}
inline const ::sita::ParamConfig& OperatorParameter::param(int index) const {
  // @@protoc_insertion_point(field_get:sita.OperatorParameter.param)
  return param_.Get(index);
}
inline ::sita::ParamConfig* OperatorParameter::mutable_param(int index) {
  // @@protoc_insertion_point(field_mutable:sita.OperatorParameter.param)
  return param_.Mutable(index);
}
inline ::sita::ParamConfig* OperatorParameter::add_param() {
  // @@protoc_insertion_point(field_add:sita.OperatorParameter.param)
  return param_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::sita::ParamConfig >&
OperatorParameter::param() const {
  // @@protoc_insertion_point(field_list:sita.OperatorParameter.param)
  return param_;
}
inline ::google::protobuf::RepeatedPtrField< ::sita::ParamConfig >*
OperatorParameter::mutable_param() {
  // @@protoc_insertion_point(field_mutable_list:sita.OperatorParameter.param)
  return &param_;
}

// optional .sita.AddOpParameter add_op_param = 100;
inline bool OperatorParameter::has_add_op_param() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void OperatorParameter::set_has_add_op_param() {
  _has_bits_[0] |= 0x00000040u;
}
inline void OperatorParameter::clear_has_add_op_param() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void OperatorParameter::clear_add_op_param() {
  if (add_op_param_ != NULL) add_op_param_->::sita::AddOpParameter::Clear();
  clear_has_add_op_param();
}
inline const ::sita::AddOpParameter& OperatorParameter::add_op_param() const {
  // @@protoc_insertion_point(field_get:sita.OperatorParameter.add_op_param)
  return add_op_param_ != NULL ? *add_op_param_ : *default_instance_->add_op_param_;
}
inline ::sita::AddOpParameter* OperatorParameter::mutable_add_op_param() {
  set_has_add_op_param();
  if (add_op_param_ == NULL) add_op_param_ = new ::sita::AddOpParameter;
  // @@protoc_insertion_point(field_mutable:sita.OperatorParameter.add_op_param)
  return add_op_param_;
}
inline ::sita::AddOpParameter* OperatorParameter::release_add_op_param() {
  clear_has_add_op_param();
  ::sita::AddOpParameter* temp = add_op_param_;
  add_op_param_ = NULL;
  return temp;
}
inline void OperatorParameter::set_allocated_add_op_param(::sita::AddOpParameter* add_op_param) {
  delete add_op_param_;
  add_op_param_ = add_op_param;
  if (add_op_param) {
    set_has_add_op_param();
  } else {
    clear_has_add_op_param();
  }
  // @@protoc_insertion_point(field_set_allocated:sita.OperatorParameter.add_op_param)
}

// optional .sita.ConvolutionOpParameter convolution_op_param = 101;
inline bool OperatorParameter::has_convolution_op_param() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void OperatorParameter::set_has_convolution_op_param() {
  _has_bits_[0] |= 0x00000080u;
}
inline void OperatorParameter::clear_has_convolution_op_param() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void OperatorParameter::clear_convolution_op_param() {
  if (convolution_op_param_ != NULL) convolution_op_param_->::sita::ConvolutionOpParameter::Clear();
  clear_has_convolution_op_param();
}
inline const ::sita::ConvolutionOpParameter& OperatorParameter::convolution_op_param() const {
  // @@protoc_insertion_point(field_get:sita.OperatorParameter.convolution_op_param)
  return convolution_op_param_ != NULL ? *convolution_op_param_ : *default_instance_->convolution_op_param_;
}
inline ::sita::ConvolutionOpParameter* OperatorParameter::mutable_convolution_op_param() {
  set_has_convolution_op_param();
  if (convolution_op_param_ == NULL) convolution_op_param_ = new ::sita::ConvolutionOpParameter;
  // @@protoc_insertion_point(field_mutable:sita.OperatorParameter.convolution_op_param)
  return convolution_op_param_;
}
inline ::sita::ConvolutionOpParameter* OperatorParameter::release_convolution_op_param() {
  clear_has_convolution_op_param();
  ::sita::ConvolutionOpParameter* temp = convolution_op_param_;
  convolution_op_param_ = NULL;
  return temp;
}
inline void OperatorParameter::set_allocated_convolution_op_param(::sita::ConvolutionOpParameter* convolution_op_param) {
  delete convolution_op_param_;
  convolution_op_param_ = convolution_op_param;
  if (convolution_op_param) {
    set_has_convolution_op_param();
  } else {
    clear_has_convolution_op_param();
  }
  // @@protoc_insertion_point(field_set_allocated:sita.OperatorParameter.convolution_op_param)
}

// -------------------------------------------------------------------

// AddOpParameter

// optional uint32 pad_h = 1 [default = 0];
inline bool AddOpParameter::has_pad_h() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AddOpParameter::set_has_pad_h() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AddOpParameter::clear_has_pad_h() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AddOpParameter::clear_pad_h() {
  pad_h_ = 0u;
  clear_has_pad_h();
}
inline ::google::protobuf::uint32 AddOpParameter::pad_h() const {
  // @@protoc_insertion_point(field_get:sita.AddOpParameter.pad_h)
  return pad_h_;
}
inline void AddOpParameter::set_pad_h(::google::protobuf::uint32 value) {
  set_has_pad_h();
  pad_h_ = value;
  // @@protoc_insertion_point(field_set:sita.AddOpParameter.pad_h)
}

// optional uint32 pad_w = 2 [default = 0];
inline bool AddOpParameter::has_pad_w() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AddOpParameter::set_has_pad_w() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AddOpParameter::clear_has_pad_w() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AddOpParameter::clear_pad_w() {
  pad_w_ = 0u;
  clear_has_pad_w();
}
inline ::google::protobuf::uint32 AddOpParameter::pad_w() const {
  // @@protoc_insertion_point(field_get:sita.AddOpParameter.pad_w)
  return pad_w_;
}
inline void AddOpParameter::set_pad_w(::google::protobuf::uint32 value) {
  set_has_pad_w();
  pad_w_ = value;
  // @@protoc_insertion_point(field_set:sita.AddOpParameter.pad_w)
}

// optional uint32 kernel_h = 3;
inline bool AddOpParameter::has_kernel_h() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AddOpParameter::set_has_kernel_h() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AddOpParameter::clear_has_kernel_h() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AddOpParameter::clear_kernel_h() {
  kernel_h_ = 0u;
  clear_has_kernel_h();
}
inline ::google::protobuf::uint32 AddOpParameter::kernel_h() const {
  // @@protoc_insertion_point(field_get:sita.AddOpParameter.kernel_h)
  return kernel_h_;
}
inline void AddOpParameter::set_kernel_h(::google::protobuf::uint32 value) {
  set_has_kernel_h();
  kernel_h_ = value;
  // @@protoc_insertion_point(field_set:sita.AddOpParameter.kernel_h)
}

// optional uint32 kernel_w = 4;
inline bool AddOpParameter::has_kernel_w() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AddOpParameter::set_has_kernel_w() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AddOpParameter::clear_has_kernel_w() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AddOpParameter::clear_kernel_w() {
  kernel_w_ = 0u;
  clear_has_kernel_w();
}
inline ::google::protobuf::uint32 AddOpParameter::kernel_w() const {
  // @@protoc_insertion_point(field_get:sita.AddOpParameter.kernel_w)
  return kernel_w_;
}
inline void AddOpParameter::set_kernel_w(::google::protobuf::uint32 value) {
  set_has_kernel_w();
  kernel_w_ = value;
  // @@protoc_insertion_point(field_set:sita.AddOpParameter.kernel_w)
}

// optional uint32 stride_h = 5;
inline bool AddOpParameter::has_stride_h() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AddOpParameter::set_has_stride_h() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AddOpParameter::clear_has_stride_h() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AddOpParameter::clear_stride_h() {
  stride_h_ = 0u;
  clear_has_stride_h();
}
inline ::google::protobuf::uint32 AddOpParameter::stride_h() const {
  // @@protoc_insertion_point(field_get:sita.AddOpParameter.stride_h)
  return stride_h_;
}
inline void AddOpParameter::set_stride_h(::google::protobuf::uint32 value) {
  set_has_stride_h();
  stride_h_ = value;
  // @@protoc_insertion_point(field_set:sita.AddOpParameter.stride_h)
}

// optional uint32 stride_w = 6;
inline bool AddOpParameter::has_stride_w() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void AddOpParameter::set_has_stride_w() {
  _has_bits_[0] |= 0x00000020u;
}
inline void AddOpParameter::clear_has_stride_w() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void AddOpParameter::clear_stride_w() {
  stride_w_ = 0u;
  clear_has_stride_w();
}
inline ::google::protobuf::uint32 AddOpParameter::stride_w() const {
  // @@protoc_insertion_point(field_get:sita.AddOpParameter.stride_w)
  return stride_w_;
}
inline void AddOpParameter::set_stride_w(::google::protobuf::uint32 value) {
  set_has_stride_w();
  stride_w_ = value;
  // @@protoc_insertion_point(field_set:sita.AddOpParameter.stride_w)
}

// -------------------------------------------------------------------

// ConvolutionOpParameter

// optional uint32 num_output = 1;
inline bool ConvolutionOpParameter::has_num_output() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConvolutionOpParameter::set_has_num_output() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConvolutionOpParameter::clear_has_num_output() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConvolutionOpParameter::clear_num_output() {
  num_output_ = 0u;
  clear_has_num_output();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::num_output() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.num_output)
  return num_output_;
}
inline void ConvolutionOpParameter::set_num_output(::google::protobuf::uint32 value) {
  set_has_num_output();
  num_output_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.num_output)
}

// optional bool bias_term = 2 [default = true];
inline bool ConvolutionOpParameter::has_bias_term() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ConvolutionOpParameter::set_has_bias_term() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ConvolutionOpParameter::clear_has_bias_term() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ConvolutionOpParameter::clear_bias_term() {
  bias_term_ = true;
  clear_has_bias_term();
}
inline bool ConvolutionOpParameter::bias_term() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.bias_term)
  return bias_term_;
}
inline void ConvolutionOpParameter::set_bias_term(bool value) {
  set_has_bias_term();
  bias_term_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.bias_term)
}

// optional uint32 pad = 3;
inline bool ConvolutionOpParameter::has_pad() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ConvolutionOpParameter::set_has_pad() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ConvolutionOpParameter::clear_has_pad() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ConvolutionOpParameter::clear_pad() {
  pad_ = 0u;
  clear_has_pad();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::pad() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.pad)
  return pad_;
}
inline void ConvolutionOpParameter::set_pad(::google::protobuf::uint32 value) {
  set_has_pad();
  pad_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.pad)
}

// optional uint32 kernel_size = 4;
inline bool ConvolutionOpParameter::has_kernel_size() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ConvolutionOpParameter::set_has_kernel_size() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ConvolutionOpParameter::clear_has_kernel_size() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ConvolutionOpParameter::clear_kernel_size() {
  kernel_size_ = 0u;
  clear_has_kernel_size();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::kernel_size() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.kernel_size)
  return kernel_size_;
}
inline void ConvolutionOpParameter::set_kernel_size(::google::protobuf::uint32 value) {
  set_has_kernel_size();
  kernel_size_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.kernel_size)
}

// optional uint32 stride = 5;
inline bool ConvolutionOpParameter::has_stride() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ConvolutionOpParameter::set_has_stride() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ConvolutionOpParameter::clear_has_stride() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ConvolutionOpParameter::clear_stride() {
  stride_ = 0u;
  clear_has_stride();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::stride() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.stride)
  return stride_;
}
inline void ConvolutionOpParameter::set_stride(::google::protobuf::uint32 value) {
  set_has_stride();
  stride_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.stride)
}

// optional uint32 dilation = 6 [default = 1];
inline bool ConvolutionOpParameter::has_dilation() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ConvolutionOpParameter::set_has_dilation() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ConvolutionOpParameter::clear_has_dilation() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ConvolutionOpParameter::clear_dilation() {
  dilation_ = 1u;
  clear_has_dilation();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::dilation() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.dilation)
  return dilation_;
}
inline void ConvolutionOpParameter::set_dilation(::google::protobuf::uint32 value) {
  set_has_dilation();
  dilation_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.dilation)
}

// optional uint32 pad_h = 7 [default = 0];
inline bool ConvolutionOpParameter::has_pad_h() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ConvolutionOpParameter::set_has_pad_h() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ConvolutionOpParameter::clear_has_pad_h() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ConvolutionOpParameter::clear_pad_h() {
  pad_h_ = 0u;
  clear_has_pad_h();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::pad_h() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.pad_h)
  return pad_h_;
}
inline void ConvolutionOpParameter::set_pad_h(::google::protobuf::uint32 value) {
  set_has_pad_h();
  pad_h_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.pad_h)
}

// optional uint32 pad_w = 8 [default = 0];
inline bool ConvolutionOpParameter::has_pad_w() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ConvolutionOpParameter::set_has_pad_w() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ConvolutionOpParameter::clear_has_pad_w() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ConvolutionOpParameter::clear_pad_w() {
  pad_w_ = 0u;
  clear_has_pad_w();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::pad_w() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.pad_w)
  return pad_w_;
}
inline void ConvolutionOpParameter::set_pad_w(::google::protobuf::uint32 value) {
  set_has_pad_w();
  pad_w_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.pad_w)
}

// optional uint32 kernel_h = 9 [default = 3];
inline bool ConvolutionOpParameter::has_kernel_h() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ConvolutionOpParameter::set_has_kernel_h() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ConvolutionOpParameter::clear_has_kernel_h() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ConvolutionOpParameter::clear_kernel_h() {
  kernel_h_ = 3u;
  clear_has_kernel_h();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::kernel_h() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.kernel_h)
  return kernel_h_;
}
inline void ConvolutionOpParameter::set_kernel_h(::google::protobuf::uint32 value) {
  set_has_kernel_h();
  kernel_h_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.kernel_h)
}

// optional uint32 kernel_w = 10 [default = 3];
inline bool ConvolutionOpParameter::has_kernel_w() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void ConvolutionOpParameter::set_has_kernel_w() {
  _has_bits_[0] |= 0x00000200u;
}
inline void ConvolutionOpParameter::clear_has_kernel_w() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void ConvolutionOpParameter::clear_kernel_w() {
  kernel_w_ = 3u;
  clear_has_kernel_w();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::kernel_w() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.kernel_w)
  return kernel_w_;
}
inline void ConvolutionOpParameter::set_kernel_w(::google::protobuf::uint32 value) {
  set_has_kernel_w();
  kernel_w_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.kernel_w)
}

// optional uint32 stride_h = 11;
inline bool ConvolutionOpParameter::has_stride_h() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void ConvolutionOpParameter::set_has_stride_h() {
  _has_bits_[0] |= 0x00000400u;
}
inline void ConvolutionOpParameter::clear_has_stride_h() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void ConvolutionOpParameter::clear_stride_h() {
  stride_h_ = 0u;
  clear_has_stride_h();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::stride_h() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.stride_h)
  return stride_h_;
}
inline void ConvolutionOpParameter::set_stride_h(::google::protobuf::uint32 value) {
  set_has_stride_h();
  stride_h_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.stride_h)
}

// optional uint32 stride_w = 12;
inline bool ConvolutionOpParameter::has_stride_w() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void ConvolutionOpParameter::set_has_stride_w() {
  _has_bits_[0] |= 0x00000800u;
}
inline void ConvolutionOpParameter::clear_has_stride_w() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void ConvolutionOpParameter::clear_stride_w() {
  stride_w_ = 0u;
  clear_has_stride_w();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::stride_w() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.stride_w)
  return stride_w_;
}
inline void ConvolutionOpParameter::set_stride_w(::google::protobuf::uint32 value) {
  set_has_stride_w();
  stride_w_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.stride_w)
}

// optional uint32 group = 13 [default = 1];
inline bool ConvolutionOpParameter::has_group() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void ConvolutionOpParameter::set_has_group() {
  _has_bits_[0] |= 0x00001000u;
}
inline void ConvolutionOpParameter::clear_has_group() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void ConvolutionOpParameter::clear_group() {
  group_ = 1u;
  clear_has_group();
}
inline ::google::protobuf::uint32 ConvolutionOpParameter::group() const {
  // @@protoc_insertion_point(field_get:sita.ConvolutionOpParameter.group)
  return group_;
}
inline void ConvolutionOpParameter::set_group(::google::protobuf::uint32 value) {
  set_has_group();
  group_ = value;
  // @@protoc_insertion_point(field_set:sita.ConvolutionOpParameter.group)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sita

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sita_5foperators_2eproto__INCLUDED
