# author: zhengwenchao@baidu.com
if ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04x86_64")
    set(CUDA_TOOLKIT_ROOT_DIR ${CMAKE_SOURCE_DIR}/../../thirdparty/for_x86/cuda-80)
    find_package(CUDA 8.0 REQUIRED)
    set(Cuda_ROOT ${CMAKE_SOURCE_DIR}/../../thirdparty/for_x86/cuda-80)
    include_directories(SYSTEM ${Cuda_ROOT}/include/)
    link_directories(${Cuda_ROOT}/lib64)
    link_directories(${Cuda_ROOT}/lib64/stubs/)
elseif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "14.04x86_64")
    set(CUDA_TOOLKIT_ROOT_DIR ${CMAKE_SOURCE_DIR}/../../../baidu/adu-3rd/cuda-80)
    find_package(CUDA 8.0 REQUIRED)
    set(Cuda_ROOT ${CMAKE_SOURCE_DIR}/../../../baidu/adu-3rd/cuda-80)
    include_directories(SYSTEM ${Cuda_ROOT}/include/)
    link_directories(${Cuda_ROOT}/lib/)
    link_directories(${Cuda_ROOT}/lib/stubs/)
elseif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04aarch64")
    set(CUDA_TOOLKIT_ROOT_DIR ${CMAKE_SOURCE_DIR}/../../thirdparty/for_arm/cuda-80)
    if (${CROSS_COMPILE} STREQUAL "16.04x86_64-16.04aarch64")
        set(CUDA_NVCC_EXECUTABLE ${CMAKE_SOURCE_DIR}/../../thirdparty/for_x86/cuda-80/bin/nvcc)
        set(CUDA_TOOLKIT_INCLUDE ${CUDA_TOOLKIT_ROOT_DIR}/include)
        set(CUDA_CUDART_LIBRARY ${CUDA_TOOLKIT_ROOT_DIR}/lib64)
    endif (${CROSS_COMPILE} STREQUAL "16.04x86_64-16.04aarch64")
    find_package(CUDA 8.0 REQUIRED)
    set(Cuda_ROOT ${CMAKE_SOURCE_DIR}/../../thirdparty/for_arm/cuda-80)
    include_directories(SYSTEM ${Cuda_ROOT}/include/)
    link_directories(${Cuda_ROOT}/lib64)
endif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04x86_64")

