if ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04x86_64")
    set(GLOG_ROOT ${CMAKE_SOURCE_DIR}/../../thirdparty/for_x86/glog)
    set(GLOG_INCLUDE_DIR ${GLOG_ROOT}/include)
    set(GLOG_LIBRARY_DIR ${GLOG_ROOT}/lib)
    include_directories(${GLOG_INCLUDE_DIR})
    link_directories(${GLOG_LIBRARY_DIR})
    file(GLOB GLOG_LIBRARIES ${GLOG_LIBRARY_DIR}/*.a)
elseif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "14.04x86_64")
    set(GLOG_LIBRARIES glog)
elseif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04aarch64")
    set(GLOG_ROOT ${CMAKE_SOURCE_DIR}/../../thirdparty/for_arm/glog/aarch64)
    set(GLOG_INCLUDE_DIR ${GLOG_ROOT}/include)
    set(GLOG_LIBRARY_DIR ${GLOG_ROOT}/lib)
    include_directories(${GLOG_INCLUDE_DIR})
    link_directories(${GLOG_LIBRARY_DIR})
    file(GLOB GLOG_LIBRARIES ${GLOG_LIBRARY_DIR}/*.a)
endif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04x86_64")
