# author: zhengwenchao@baidu.com

if ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04x86_64")
    set(OpenCV_ROOT ${CMAKE_SOURCE_DIR}/../../thirdparty/for_x86/opencv)
    set(OpenCV_INCLUDE_DIRS ${OpenCV_ROOT}/include)
    set(OpenCV_LIBRARY_DIRS ${OpenCV_ROOT}/lib)
    include_directories(SYSTEM ${OpenCV_INCLUDE_DIRS})
    link_directories(${OpenCV_LIBRARY_DIRS})
    file(GLOB OpenCV_LIBS ${OpenCV_LIBRARY_DIRS}/libopencv_*.so)
elseif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "14.04x86_64")
    set(OpenCV_ROOT ${CMAKE_SOURCE_DIR}/../../adu-3rd/opencv)
    set(OpenCV_INCLUDE_DIRS ${OpenCV_ROOT}/include)
    set(OpenCV_LIBRARY_DIRS ${OpenCV_ROOT}/lib)
    include_directories(SYSTEM ${OpenCV_INCLUDE_DIRS})
    link_directories(${OpenCV_LIBRARY_DIRS})
    file(GLOB OpenCV_LIBS ${OpenCV_LIBRARY_DIRS}/libopencv_*.so)
elseif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04aarch64")
    set(OpenCV_DIR ${CMAKE_SOURCE_DIR}/../../thirdparty/for_arm/ros-base/aarch64)
    find_package(OpenCV 3.2 EXACT REQUIRED)
    message("OpenCV dirs : " ${OpenCV_INCLUDE_DIRS})
    include_directories(SYSTEM ${OpenCV_INCLUDE_DIRS})
    link_directories(${OpenCV_LIBRARY_DIRS})
endif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04x86_64")
