# author: yanhe@baidu.com

if ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04x86_64")
    set(XLOG_DIR "${CMAKE_SOURCE_DIR}/../../thirdparty/for_x86/xlog")
    if(EXISTS ${XLOG_DIR})
        message("Use ../../thirdparty/for_x86/xlog")
        set(XLOG_ROOT "${CMAKE_SOURCE_DIR}/../../thirdparty/for_x86/xlog")
        set(XLOG_INCLUDE_DIR "${XLOG_ROOT}/include")
        set(XLOG_LINK_DIR "${XLOG_ROOT}/lib")
        file(GLOB XLOG_LIBRARIES "${XLOG_LINK_DIR}/libxlog.a")
        include_directories(SYSTEM ${XLOG_INCLUDE_DIR})
        link_directories(${XLOG_LINK_DIR})
    else()
        message("Use xlog local")
        find_package(Xlog REQUIRED)
    endif()
elseif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "14.04x86_64")
    set(XLOG_DIR "${CMAKE_SOURCE_DIR}/../../adu/libs-xlog")
    if(EXISTS ${XLOG_DIR})
        message("Use baidu/adu/libs-xlog")
        set(XLOG_ROOT "${CMAKE_SOURCE_DIR}/../../adu/libs-xlog")
        set(XLOG_INCLUDE_DIR "${XLOG_ROOT}/include")
        set(XLOG_LINK_DIR "${XLOG_ROOT}/lib")
        file(GLOB XLOG_LIBRARIES "${XLOG_LINK_DIR}/libxlog.a")
        include_directories(SYSTEM ${XLOG_INCLUDE_DIR})
        link_directories(${XLOG_LINK_DIR})
    else()
        message("Use xlog local")
        find_package(Xlog REQUIRED)
    endif()
elseif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04aarch64")
    set(XLOG_DIR "${CMAKE_SOURCE_DIR}/../../thirdparty/for_arm/xlog/aarch64")
    if(EXISTS ${XLOG_DIR})
        message("Use ../../thirdparty/for_arm/xlog")
        set(XLOG_ROOT "${CMAKE_SOURCE_DIR}/../../thirdparty/for_arm/xlog/aarch64")
        set(XLOG_INCLUDE_DIR "${XLOG_ROOT}/include")
        set(XLOG_LINK_DIR "${XLOG_ROOT}/lib")
        file(GLOB XLOG_LIBRARIES "${XLOG_LINK_DIR}/libxlog.a")
        include_directories(SYSTEM ${XLOG_INCLUDE_DIR})
        link_directories(${XLOG_LINK_DIR})
    else()
        message("Use xlog local")
        find_package(Xlog REQUIRED)
    endif()
endif ("$ENV{SYSTEM_ENVIRONMENT}" STREQUAL "16.04x86_64")
